// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storedb

import (
	"database/sql"
)

type Chat struct {
	Jid           string
	Kind          string
	Name          sql.NullString
	LastMessageTs sql.NullInt64
	Archived      int64
	Pinned        int64
	MutedUntil    int64
	Unread        int64
}

type Contact struct {
	Jid          string
	Phone        sql.NullString
	PushName     sql.NullString
	FullName     sql.NullString
	FirstName    sql.NullString
	BusinessName sql.NullString
	SystemName   sql.NullString
	UpdatedAt    int64
}

type ContactAlias struct {
	Jid       string
	Alias     string
	Notes     sql.NullString
	UpdatedAt int64
}

type ContactTag struct {
	Jid       string
	Tag       string
	UpdatedAt int64
}

type Group struct {
	Jid             string
	Name            sql.NullString
	OwnerJid        sql.NullString
	CreatedTs       sql.NullInt64
	IsParent        int64
	LinkedParentJid sql.NullString
	LeftAt          sql.NullInt64
	UpdatedAt       int64
}

type GroupParticipant struct {
	GroupJid  string
	UserJid   string
	Role      sql.NullString
	UpdatedAt int64
}

type Message struct {
	Rowid           int64
	ChatJid         string
	ChatName        sql.NullString
	MsgID           string
	SenderJid       sql.NullString
	SenderName      sql.NullString
	Ts              int64
	FromMe          int64
	Text            sql.NullString
	DisplayText     sql.NullString
	IsForwarded     int64
	ForwardingScore int64
	ReactionToID    sql.NullString
	ReactionEmoji   sql.NullString
	MediaType       sql.NullString
	MediaCaption    sql.NullString
	Filename        sql.NullString
	MimeType        sql.NullString
	DirectPath      sql.NullString
	MediaKey        []byte
	FileSha256      []byte
	FileEncSha256   []byte
	FileLength      sql.NullInt64
	LocalPath       sql.NullString
	DownloadedAt    sql.NullInt64
	Revoked         int64
	DeletedForMe    int64
	Edited          int64
	EditedTs        int64
	Buttons         sql.NullString
}

type MessagesFt struct {
	Rowid        int64
	Text         sql.NullString
	MediaCaption sql.NullString
	Filename     sql.NullString
	ChatName     sql.NullString
	SenderName   sql.NullString
	DisplayText  sql.NullString
}

type Poll struct {
	ChatJid         string
	MsgID           string
	SenderJid       sql.NullString
	Question        string
	OptionsJson     string
	SelectableCount int64
	CreatedTs       int64
}

type PollVote struct {
	ChatJid             string
	PollMsgID           string
	VoterJid            string
	VoteMsgID           string
	SelectedOptionsJson string
	Ts                  int64
}

type Starred struct {
	ChatJid   string
	MsgID     string
	SenderJid sql.NullString
	FromMe    int64
	StarredAt int64
}
